"""Compile normalized intent into a contained, opt-in local Codex bundle."""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Mapping

from runtime.common.adapter import ArtifactPlan
from runtime.common.normalization import NormalizedAgent, children_by_parent

ROOT = Path(__file__).resolve().parents[2]
NOTICE = "GENERATED BY opencode-agent-toolkit. DO NOT EDIT DIRECTLY."
REASONING_LEVELS = {"low", "medium", "high", "xhigh", "max", "ultra"}

# Native local-agent fields are documented at:
# https://learn.chatgpt.com/docs/agent-configuration/subagents
# runtime.json is our capability report, NOT a Codex configuration file.
LIMITATIONS = (
    "Fine-grained allow/ask/deny tool, path, secret, shell and network rules are instruction-only; "
    "Codex does not enforce the OpenCode permission table.",
    "Only edit=allow roles request workspace-write; edit=ask or deny requests read-only. "
    "Live parent permissions can override custom-agent sandbox defaults, so this is not an immutable security boundary.",
    "Leaf agents disable native multi-agent tools via [agents] enabled=false. "
    "Lead child allowlists and maximum graph depth remain instruction-only; arbitrary native role spawning is not allowlisted by this bundle.",
    "Step budgets, concurrency policy, retries, stalls and cost guards are instruction-only or unavailable; "
    "OpenCode watchdog/plugin enforcement is not installed in Codex.",
    "Model availability and model-specific reasoning support are not checked offline. "
    "Omitted models inherit local Codex defaults.",
    "No canonical local skill source is configured; no skills are generated. "
    "Memory integration, MCP and remote Agents/Skills publication are not implemented.",
    "The staged bundle is not auto-discovered from the project root. Install agent TOML files explicitly "
    "and ask Codex to read the generated AGENTS.md; the primary role is not changed automatically.",
)


class CodexAdapter:
    """Render only from the normalized graph, without reading canonical files."""

    name = "codex"

    def __init__(self, root: Path = ROOT, environ: Mapping[str, str] | None = None) -> None:
        self.root = root
        self.output_dir = root / ".generated" / "codex"
        self.environ = dict(os.environ if environ is None else environ)

    def _policy(self, spec: NormalizedAgent) -> dict:
        extension = spec.extensions.get("codex", {})
        if not isinstance(extension, dict):
            raise ValueError(f"{spec.name}: codex extension must be an object")
        unknown = set(extension) - {"model", "reasoning"}
        if unknown:
            raise ValueError(f"{spec.name}: unsupported codex extension keys: {', '.join(sorted(unknown))}")
        for key, value in extension.items():
            if not isinstance(value, str) or not value.strip():
                raise ValueError(f"{spec.name}: codex.{key} must be a non-empty string")
        suffix = spec.model_env.removeprefix("MODEL_")
        tier = spec.tier.upper()
        model = (self.environ.get(f"CODEX_MODEL_{suffix}") or extension.get("model")
                 or self.environ.get(f"CODEX_MODEL_{tier}"))
        reasoning = (self.environ.get(f"CODEX_REASONING_{suffix}") or extension.get("reasoning")
                     or self.environ.get(f"CODEX_REASONING_{tier}") or spec.tier)
        if model is not None and (not isinstance(model, str) or not model.strip() or any(c.isspace() for c in model)):
            raise ValueError(f"{spec.name}: Codex model must be a non-empty model identifier without whitespace")
        if reasoning not in REASONING_LEVELS:
            raise ValueError(f"{spec.name}: Codex reasoning must be one of {sorted(REASONING_LEVELS)}")
        return {
            "tier": spec.tier,
            "model": model,
            "reasoning": reasoning,
            "sandbox_mode": "workspace-write" if spec.permissions.get("edit") == "allow" else "read-only",
        }

    def _instructions(self, spec: NormalizedAgent, children: list[str]) -> str:
        delegation = (
            "Delegate only to these canonical children: " + ", ".join(f"`{name}`" for name in children) + "."
            if children else "Leaf agent: do not delegate or spawn any child agents."
        )
        permissions = json.dumps(spec.permissions, indent=2, ensure_ascii=False)
        return "\n\n".join(part for part in (
            f"<!-- {NOTICE} -->\n# {spec.name}\n\n{spec.description}",
            spec.prompt,
            spec.default_prompt,
            "## Codex delegation and budget intent\n"
            + delegation + "\nKeep delegation depth at most two edges from the primary agent. "
            "Reuse completed handoffs; independent reviewers may re-read primary evidence. "
            "Do not fill concurrency slots without independent useful work.\n"
            f"Canonical step budget: {spec.steps} (instruction-only in Codex).",
            "## Canonical permission intent\n"
            "Honor this complete canonical table: allow permits only the matching scope, ask requires "
            "explicit approval, and deny forbids the operation. Preserve secret/private-path and destructive "
            "Git/infrastructure restrictions. These are instructions, not native per-tool enforcement. "
            "Do not interpret an available Codex tool or inherited permission as authorization.\n\n"
            f"```json\n{permissions}\n```",
            "## Local Codex limitations\n" + "\n".join(f"- {item}" for item in LIMITATIONS),
        ) if part).rstrip() + "\n"

    def _agent_toml(self, spec: NormalizedAgent, instructions: str, policy: dict, children: list[str]) -> bytes:
        fields = {
            "name": spec.name,
            "description": spec.description,
            "developer_instructions": instructions,
            "model_reasoning_effort": policy["reasoning"],
            "sandbox_mode": policy["sandbox_mode"],
        }
        if policy["model"] is not None:
            fields["model"] = policy["model"]
        lines = [f"# {NOTICE}", "# Regenerate with: oc sync codex"]
        lines.extend(f"{key} = {json.dumps(value, ensure_ascii=False)}" for key, value in fields.items())
        if not children:
            lines.extend(["", "[agents]", "enabled = false"])
        return ("\n".join(lines) + "\n").encode()

    def plan(self, specs: Mapping[str, NormalizedAgent]) -> ArtifactPlan:
        children = children_by_parent(dict(specs))
        primary = next(name for name in sorted(specs) if specs[name].mode == "primary")
        policies = {name: self._policy(specs[name]) for name in sorted(specs)}
        files = {}
        reports = {}
        for name in sorted(specs):
            spec = specs[name]
            instructions = self._instructions(spec, children[name])
            files[self.output_dir / "agents" / f"{name}.md"] = instructions.encode()
            files[self.output_dir / "agents" / f"{name}.toml"] = self._agent_toml(spec, instructions, policies[name], children[name])
            reports[name] = {
                **policies[name], "description": spec.description, "mode": spec.mode,
                "parents": list(spec.parents), "children": children[name],
                "steps": spec.steps, "permissions": spec.permissions,
                "source": f"agents/{name}",
            }

        topology = "\n".join(
            f"- `{name}` -> " + ", ".join(f"`{child}`" for child in children[name])
            for name in sorted(specs) if children[name]
        )
        overview = (
            f"<!-- {NOTICE} -->\n# Generated Codex runtime instructions\n\n"
            "## Source of truth\n"
            "The toolkit's `agents/<name>/` definitions are canonical. This bundle is disposable; "
            "regenerate with `oc sync codex`, never edit generated files. "
            "`runtime.json` is a toolkit report, not native Codex configuration.\n\n"
            "## Agent topology and workflow\n"
            f"Begin by selecting the `{primary}` role explicitly; installation does not change Codex's default role. "
            "Installed native agent TOML embeds its full instructions; when using the standalone Markdown instead, "
            "explicitly read the assigned `.generated/codex/agents/<name>.md` from the toolkit checkout before work. "
            "Lead delegation is limited to the following graph; all other roles are bounded leaves:\n\n"
            f"{topology}\n\n"
            "Keep the graph shallow (at most two edges). Reuse completed handoffs. "
            "Separate facts, assumptions and recommendations; report verification and residual risk. "
            "Independent review must not be performed solely by the producer.\n\n"
            "## Permissions and Git safety\n"
            "Each role's generated instructions contain its full canonical permission table and shared policy. "
            "Honor allow/ask/deny, protect private paths and secrets, and preserve destructive Git/infrastructure denials. "
            "Inspect status/diff before changes, preserve unrelated user work, run relevant tests and prefer PR-based delivery. "
            "Tool availability is not permission to bypass canonical policy.\n\n"
            "## Activation\n"
            "Generation does not edit repository-root AGENTS.md or personal Codex configuration. "
            "After reviewing for existing-name conflicts, explicitly install the generated `agents/*.toml` "
            "in your target project's `.codex/agents/`. Ask Codex to read this generated AGENTS.md explicitly. "
            "Use a local Codex version supporting custom-agent TOML and restart/reload as required by that runtime.\n\n"
            "## Runtime limitations\n" + "\n".join(f"- {item}" for item in LIMITATIONS) + "\n"
        )
        files[self.output_dir / "AGENTS.md"] = overview.encode()
        report = {
            "generated_by": "opencode-agent-toolkit", "notice": NOTICE,
            "format": "toolkit-codex-capability-report-v1", "primary_agent": primary,
            "agents": reports, "skills": [], "warnings": list(LIMITATIONS),
            "capabilities": {
                "local_agent_toml": "supported; explicit installation required",
                "model_reasoning_mapping": "configured locally; model compatibility unverified",
                "leaf_delegation": "native agents.enabled=false",
                "permission_patterns": "instruction-only",
                "lead_allowlists_depth_steps": "instruction-only",
                "memory": "not implemented", "mcp": "not implemented",
                "remote_publication": "not implemented",
            },
        }
        files[self.output_dir / "runtime.json"] = (json.dumps(report, indent=2, ensure_ascii=False) + "\n").encode()
        # Validate ancestors before scanning or reading obsolete output. A matching
        # filename alone does not establish ownership of a user-added file.
        ArtifactPlan(self.root, files).validate()
        stale = []
        for pattern in ("*.md", "*.toml"):
            for path in (self.output_dir / "agents").glob(pattern):
                if path in files:
                    continue
                ArtifactPlan(self.root, {path: b""}).validate()
                with path.open("rb") as stream:
                    header = stream.readline(256)
                if NOTICE.encode() in header:
                    stale.append(path)
        notes = (f"Agents: {len(specs)}; canonical skills: 0", "Model policy:", *(
            f"  {name}: tier={policy['tier']} model={policy['model'] or '(inherit local Codex default)'} reasoning={policy['reasoning']}"
            for name, policy in policies.items()
        ), "Capability warnings:", *(f"  {item}" for item in LIMITATIONS))
        return ArtifactPlan(self.root, files, tuple(sorted(stale)), notes)

    def generate(self, specs: Mapping[str, NormalizedAgent]) -> tuple[Path, ...]:
        return self.plan(specs).write()
