#!/usr/bin/env python3
"""Prepare already-installed memory for a native OpenCode launch.

No clone, pull, install or build is allowed here. The configured plugin target is
printed on stdout so the launcher can place it in highest-precedence inline config.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
from pathlib import Path

TRUTHY = {"1", "true", "yes", "on"}
ROOT = Path(__file__).resolve().parents[1]
V2_WRAPPER = ROOT / ".generated" / "plugins" / "opencode-memory-plugin-v2"


def enabled() -> bool:
    raw = os.getenv("OPENCODE_MEMORY_ENABLED") or os.getenv("OAT_MEMORY_ENABLED") or ""
    return raw.strip().lower() in TRUTHY


def prepare_v2_wrapper(entry: Path) -> Path:
    if V2_WRAPPER.is_symlink():
        raise RuntimeError(f"refusing symlinked V2 memory wrapper: {V2_WRAPPER}")
    V2_WRAPPER.mkdir(parents=True, exist_ok=True)
    (V2_WRAPPER / "index.js").write_text(
        "// Generated by native_memory.py; no network or install occurs here.\n"
        f"export {{ default }} from {json.dumps(entry.resolve().as_uri())}\n"
    )
    (V2_WRAPPER / "package.json").write_text(
        json.dumps(
            {
                "name": "oat-opencode-memory-plugin-v2",
                "version": "0.0.0",
                "private": True,
                "type": "module",
                "exports": "./index.js",
            },
            separators=(",", ":"),
        )
        + "\n"
    )
    return V2_WRAPPER.resolve()


def render_v2_context(config: Path, plugin: Path) -> None:
    cli = plugin / "dist" / "cli.js"
    if not cli.is_file() or not shutil.which("node"):
        return
    payload = json.loads(config.read_text())
    env = os.environ.copy()
    env["OAT_MEMORY_AUTO_SYNC"] = "0"
    env["OPENCODE_MEMORY_AUTO_SYNC"] = "0"
    env["OAT_MEMORY_STRICT"] = "0"
    env["OPENCODE_MEMORY_STRICT"] = "0"
    for name, spec in payload.get("agents", {}).items():
        try:
            result = subprocess.run(
                ["node", str(cli), "render", "--agent", name, "--cwd", os.getcwd()],
                env=env,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=5,
                check=False,
            )
            if result.returncode == 0 and result.stdout.strip():
                spec["system"] = spec.get("system", "").rstrip() + "\n\n" + result.stdout.strip() + "\n"
        except (OSError, subprocess.SubprocessError):
            continue
    config.write_text(json.dumps(payload, indent=2) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--major", choices=("1", "2"), required=True)
    args = parser.parse_args()
    if not enabled():
        return 0

    data = Path(os.getenv("XDG_DATA_HOME") or Path.home() / ".local/share")
    plugin = Path(
        os.getenv("OAT_MEMORY_PLUGIN_DIR")
        or data / "opencode-agent-toolkit" / "plugins" / "opencode-memory-plugin"
    ).expanduser()
    vault = Path(
        os.getenv("OPENCODE_MEMORY_DIR")
        or os.getenv("OAT_MEMORY_DIR")
        or data / "opencode-agent-toolkit" / "memory"
    ).expanduser()
    entry = plugin / "dist" / ("v2.js" if args.major == "2" else "v1.js")
    if not entry.is_file() or not vault.is_dir():
        print("OpenCode memory unavailable locally; continuing without memory", file=os.sys.stderr)
        return 0

    if args.major == "2":
        target = prepare_v2_wrapper(entry)
        render_v2_context(ROOT / "opencode.v2.jsonc", plugin)
    else:
        target = entry.resolve()

    # stdout is machine-readable: launcher injects this target into inline config.
    print(target)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
