#!/usr/bin/env python3
"""Prepare the already-installed memory plugin for a native OpenCode launch.

No clone, pull, install or build is allowed here. Installation belongs to
`just install`; the daily `oc` path only wires the local plugin into the
highest-precedence OpenCode configuration and renders read-only context.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
from pathlib import Path

TRUTHY = {"1", "true", "yes", "on"}
ROOT = Path(__file__).resolve().parents[1]


def wrapper_dir() -> Path:
    return Path(
        os.getenv("OAT_MEMORY_WRAPPER_DIR")
        or ROOT / ".generated" / "plugins" / "opencode-memory-plugin-v2"
    ).expanduser()


def enabled() -> bool:
    raw = os.getenv("OPENCODE_MEMORY_ENABLED") or os.getenv("OAT_MEMORY_ENABLED") or ""
    return raw.strip().lower() in TRUTHY


def plugin_dir() -> Path:
    data = Path(os.getenv("XDG_DATA_HOME") or Path.home() / ".local/share")
    return Path(
        os.getenv("OAT_MEMORY_PLUGIN_DIR")
        or data / "opencode-agent-toolkit" / "plugins" / "opencode-memory-plugin"
    ).expanduser()


def vault_dir() -> Path:
    return Path(
        os.getenv("OPENCODE_MEMORY_DIR")
        or os.getenv("OAT_MEMORY_DIR")
        or Path.home() / "opencode-memory"
    ).expanduser()


def prepare_v2_wrapper(entry: Path) -> Path:
    wrapper = wrapper_dir()
    if wrapper.is_symlink():
        raise RuntimeError(f"refusing symlinked V2 memory wrapper: {wrapper}")
    wrapper.mkdir(parents=True, exist_ok=True)
    (wrapper / "index.js").write_text(
        "// Generated by native_memory.py; no network or install occurs here.\n"
        f"export {{ default }} from {json.dumps(entry.resolve().as_uri())}\n"
    )
    (wrapper / "package.json").write_text(
        json.dumps(
            {
                "name": "oat-opencode-memory-plugin-v2",
                "version": "0.0.0",
                "private": True,
                "type": "module",
                "exports": "./index.js",
            },
            separators=(",", ":"),
        )
        + "\n"
    )
    return wrapper.resolve()


def render_context(plugin: Path, context_file: Path) -> bool:
    cli = plugin / "dist" / "cli.js"
    node = shutil.which("node")
    if not cli.is_file() or not node:
        return False
    env = os.environ.copy()
    env["OAT_MEMORY_AUTO_SYNC"] = "0"
    env["OPENCODE_MEMORY_AUTO_SYNC"] = "0"
    env["OAT_MEMORY_STRICT"] = "0"
    env["OPENCODE_MEMORY_STRICT"] = "0"
    try:
        result = subprocess.run(
            [node, str(cli), "render", "--agent", "orchestrator", "--cwd", os.getcwd()],
            env=env,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=8,
            check=False,
        )
    except (OSError, subprocess.SubprocessError) as error:
        print(f"OpenCode memory context unavailable: {error}", file=os.sys.stderr)
        return False
    if result.returncode != 0 or not result.stdout.strip():
        detail = (result.stderr or result.stdout or "render returned no context").strip()
        print(f"OpenCode memory context unavailable: {detail}", file=os.sys.stderr)
        return False
    context_file.parent.mkdir(parents=True, exist_ok=True)
    context_file.write_text(result.stdout.rstrip() + "\n")
    try:
        context_file.chmod(0o600)
    except OSError:
        pass
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--major", choices=("2",), default="2")
    parser.add_argument("--context-file")
    args = parser.parse_args()
    if not enabled():
        return 0

    plugin = plugin_dir()
    vault = vault_dir()
    entry = plugin / "dist" / "v2.js"
    if not entry.is_file() or not vault.is_dir():
        print("OpenCode memory unavailable locally; run 'just install'.", file=os.sys.stderr)
        return 0

    target = prepare_v2_wrapper(entry)
    if args.context_file:
        context = Path(args.context_file).expanduser().resolve()
        if not render_context(plugin, context):
            try:
                context.unlink(missing_ok=True)
            except OSError:
                pass

    # stdout is machine-readable: the launcher injects this local plugin target.
    print(target)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
