"""Stable OpenCode 2 rendering from the runtime-neutral normalized agent graph."""
from __future__ import annotations

import copy
import json
from pathlib import Path
from typing import Mapping

from runtime.common.normalization import NormalizedAgent, NormalizedSkill, children_by_parent
from runtime.common.adapter import ArtifactPlan

ROOT = Path(__file__).resolve().parents[2]
GENERATED_DIR = ROOT / ".generated"
GENERATED_PROMPTS_DIR = GENERATED_DIR / "prompts"
ACTION_MAP = {"bash": "shell", "task": "subagent"}
PROMPT_ACTION_LABELS = {"bash": "bash / shell", "task": "task / subagent"}

COMMANDS = {
    "auto": ("Automatically route and execute a task", "Execute $ARGUMENTS using the minimum sufficient path; verify the result."),
    "plan": ("Create a plan without implementing it", "Plan $ARGUMENTS. Explain scope, steps, tests and important risks. Do not implement."),
    "ship": ("Implement with tests and independent review", "Implement $ARGUMENTS. Use the smallest useful delegation path, run relevant tests and independent review, then report evidence."),
    "review": ("Run an independent review", "Review $ARGUMENTS via review-lead and report actionable findings."),
    "architecture": ("Design architecture from repository evidence", "Design $ARGUMENTS via platform-architect. Explain trade-offs, migration, rollback and residual risk."),
    "security": ("Run an adaptive security review", "Security-review $ARGUMENTS via security-lead and prioritize verified findings."),
    "debug": ("Reproduce, fix and test", "Debug $ARGUMENTS via orchestrator. Reproduce, fix, add regression coverage and verify."),
    "incident": ("Investigate and remediate an incident", "Investigate $ARGUMENTS with evidence-first debugging and relevant specialists; report blast radius and verification."),
    "cost": ("Analyze cost and cost-performance trade-offs", "Analyze $ARGUMENTS via platform-architect using FinOps and relevant specialists."),
}

GENERATED_AGENT_KEYS = {
    "description", "mode", "model", "prompt", "system", "steps", "permission", "permissions",
}
COMPACTION = {"auto": True, "keep": {"tokens": 15000}, "buffer": 20000}


def task_permissions(name: str, specs: Mapping[str, NormalizedAgent]) -> dict[str, str]:
    children = children_by_parent(dict(specs))[name]
    return {"*": "deny", **{child: "allow" for child in children}}


def source_permissions(name: str, specs: Mapping[str, NormalizedAgent]) -> dict:
    return {"task": task_permissions(name, specs), **copy.deepcopy(specs[name].permissions)}


def permission_rules(name: str, specs: Mapping[str, NormalizedAgent]) -> list[dict]:
    rules: list[dict] = []
    for key, value in source_permissions(name, specs).items():
        action = ACTION_MAP.get(key, key)
        resources = {"*": value} if isinstance(value, str) else value
        for resource, effect in resources.items():
            rules.append({"action": action, "resource": resource, "effect": effect})
    return rules


class OpenCodeAdapter:
    name = "opencode"

    def __init__(self, root: Path = ROOT) -> None:
        self.root = root
        self.generated_dir = root / ".generated"
        self.generated_prompts_dir = self.generated_dir / "prompts"
        self.skills_dir = root / ".opencode" / "skills"

    @staticmethod
    def render_skill(skill: NormalizedSkill) -> bytes:
        return (
            "---\n"
            f"name: {skill.name}\n"
            f"description: {json.dumps(skill.description, ensure_ascii=False)}\n"
            "---\n\n"
            "<!-- GENERATED BY opencode-agent-toolkit. DO NOT EDIT DIRECTLY. -->\n\n"
            f"{skill.prompt}\n"
        ).encode()

    def render_capabilities(self, name: str, specs: Mapping[str, NormalizedAgent]) -> str:
        grouped: dict[str, dict[str, list[str]]] = {effect: {} for effect in ("allow", "ask", "deny")}
        for action, value in source_permissions(name, specs).items():
            label = PROMPT_ACTION_LABELS.get(action, action)
            resources = {"*": value} if isinstance(value, str) else value
            for resource, effect in resources.items():
                grouped[effect].setdefault(label, []).append(resource)

        lines = [
            "## Effective capabilities",
            "This capability map is generated from the same permissions used by OpenCode.",
        ]
        for effect, heading in (("allow", "ALLOW"), ("ask", "ASK"), ("deny", "DENY")):
            lines.extend(["", f"### {heading}"])
            actions = grouped[effect]
            if not actions:
                lines.append("- None.")
            for action, resources in actions.items():
                lines.append(f"- `{action}`: " + ", ".join(f"`{resource}`" for resource in resources))
        return "\n".join(lines)

    def render_prompt(self, spec: NormalizedAgent, specs: Mapping[str, NormalizedAgent]) -> str:
        default_prompt = (self.root / "agents" / "_defaults" / "prompt.md").read_text().strip()
        parts = [f"# Role\n{spec.description}"]
        if spec.prompt:
            parts.append(spec.prompt)
        if default_prompt:
            parts.append(default_prompt)
        parts.append(self.render_capabilities(spec.name, specs))
        return "\n\n".join(parts).rstrip() + "\n"

    def source_plan(self, specs: Mapping[str, NormalizedAgent]) -> ArtifactPlan:
        files = {
            self.generated_prompts_dir / f"{name}.md": self.render_prompt(spec, specs).encode()
            for name, spec in specs.items()
        }
        children = children_by_parent(dict(specs))
        manifest = {
            name: {
                "description": spec.description,
                "mode": spec.mode,
                "model_env": spec.model_env,
                "tier": spec.tier,
                "model_profile": spec.model_profile,
                "steps": spec.steps,
                "parents": list(spec.parents),
                "children": children[name],
                "source": f"agents/{name}",
            }
            for name, spec in specs.items()
        }
        files[self.generated_dir / "agents.json"] = (json.dumps(manifest, indent=2) + "\n").encode()
        stale = tuple(path for path in self.generated_prompts_dir.glob("*.md") if path not in files)
        return ArtifactPlan(self.root, files, stale)

    def agent_entry(self, name: str, specs: Mapping[str, NormalizedAgent]) -> dict:
        spec = specs[name]
        opencode = spec.extensions["opencode"]
        collisions = GENERATED_AGENT_KEYS & set(opencode)
        if collisions:
            raise SystemExit(f"{name}: opencode cannot override generated keys: {', '.join(sorted(collisions))}")
        entry = {
            "description": spec.description,
            "mode": spec.mode,
            "model": f"{{env:{spec.model_env}}}",
            "system": f"{{file:./.generated/prompts/{name}.md}}",
            "steps": spec.steps,
            "permissions": permission_rules(name, specs),
        }
        entry.update(opencode)
        return entry

    def build(self, specs: Mapping[str, NormalizedAgent]) -> dict:
        primary = next(name for name, spec in specs.items() if spec.mode == "primary")
        return {
            "$schema": "https://opencode.ai/config.json",
            "default_agent": primary,
            "compaction": COMPACTION,
            "agents": {name: self.agent_entry(name, specs) for name in sorted(specs)},
            "commands": {
                name: {"description": desc, "template": template, "agent": primary}
                for name, (desc, template) in COMMANDS.items()
            },
            "plugins": [],
            "experimental": {"subagent_depth": 2},
        }

    def plan(self, specs: Mapping[str, NormalizedAgent], skills: Mapping[str, NormalizedSkill] | None = None) -> ArtifactPlan:
        skills = skills or {}
        source_plan = self.source_plan(specs)
        files = dict(source_plan.files)
        files[self.root / "opencode.jsonc"] = (json.dumps(self.build(specs), indent=2) + "\n").encode()
        for name in sorted(skills):
            files[self.skills_dir / name / "SKILL.md"] = self.render_skill(skills[name])
        stale = list(source_plan.stale)
        if self.skills_dir.exists():
            for path in self.skills_dir.glob("*/SKILL.md"):
                if path in files:
                    continue
                if b"GENERATED BY opencode-agent-toolkit" in path.read_bytes()[:512]:
                    stale.append(path)
        return ArtifactPlan(self.root, files, tuple(sorted(stale)))

    def generate(self, specs: Mapping[str, NormalizedAgent], skills: Mapping[str, NormalizedSkill] | None = None) -> tuple[Path, ...]:
        self.plan(specs, skills).write()
        return (self.root / "opencode.jsonc",)


def write_generated_sources(specs: Mapping[str, NormalizedAgent]) -> None:
    OpenCodeAdapter().source_plan(specs).write()
